version: 2
jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no root@$GOWON_HOST_IP "cd ./gowon.ca && /bin/bash ./deploy.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - approve:
          type: approval

      - deploy:
          context:
            - gowon
          requires:
            - approve
